"""create api_keys table

Revision ID: 005
Revises: 004
Create Date: 2025-11-24 00:25:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='API密钥唯一标识'),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False, comment='用户ID'),
        sa.Column('provider', sa.String(length=50), nullable=False, comment='服务提供商'),
        sa.Column('name', sa.String(length=100), nullable=False, comment='密钥名称'),
        sa.Column('api_key', sa.Text(), nullable=False, comment='API密钥（加密存储）'),
        sa.Column('base_url', sa.String(length=500), nullable=True, comment='API基础URL'),
        sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='密钥状态：active（激活）、inactive（未激活）、expired（过期）'),
        sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='最后使用时间'),
        sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False, comment='使用次数统计'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='API密钥表 - 存储用户配置的AI服务API密钥'
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_keys_provider'), 'api_keys', ['provider'], unique=False)
    op.create_index(op.f('ix_api_keys_status'), 'api_keys', ['status'], unique=False)
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    
    # 为 api_keys 表创建更新时间触发器
    op.execute("""
        CREATE TRIGGER update_api_keys_updated_at
            BEFORE UPDATE ON api_keys
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除触发器
    op.execute("DROP TRIGGER IF EXISTS update_api_keys_updated_at ON api_keys")
    
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_status'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_provider'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
